Starting job script for server
Activating conda environment for server
Starting job script for client 1
Starting job script for client 2
Activating conda environment for client 1
Activating conda environment for client 2
Server is listening on port 8001
server ready file exists
CLient 1 connecting via 8001
Accepted connection from ('10.158.1.19', 37910)
Server is listening on port 8002
server ready file exists
CLient 2 connecting via 8002
Accepted connection from ('10.158.1.20', 51728)
SERVER: time taken to establish connections is 1.3824949264526367
RAM usage: 111.81 MB
RAM usage: 8898.43 MB
RAM usage: 8724.00 MB
/mnt/beegfs/home/swaminathan/ppREGENIE/ppREGENIE/cluster_blocked/client.py:461: RuntimeWarning: invalid value encountered in sqrt
  stds = np.sqrt(aggregated_vector - sum_5)[:-num_new_elements]
/mnt/beegfs/home/swaminathan/ppREGENIE/ppREGENIE/cluster_blocked/client.py:461: RuntimeWarning: invalid value encountered in sqrt
  stds = np.sqrt(aggregated_vector - sum_5)[:-num_new_elements]
RAM usage: 161717.85 MB
DONE! Took for all 60 blocks, 1917.353140115738
RAM usage: 38075.66 MB
RAM usage: 38101.98 MB
printing delta for p = 1 with parameters (612794, 75, 1, 2, 9178, 2, 8214, 3, 74)
run_server.sh: line 9: 3806690 Killed                  python -u server.py --number_of_clients $7 --base_port $1 --number_of_samples $2 --number_of_snps $3 --number_of_covariates $4 --number_of_blocks $5 --number_of_folds $6 --number_of_blocks_per_run $8
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=873167.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: tcml-node18: task 0: Out Of Memory
Traceback (most recent call last):
  File "/mnt/beegfs/home/swaminathan/ppREGENIE/ppREGENIE/cluster_blocked/client.py", line 630, in <module>
Traceback (most recent call last):
  File "/mnt/beegfs/home/swaminathan/ppREGENIE/ppREGENIE/cluster_blocked/client.py", line 630, in <module>
    cProfile.run('main()', '/home/swaminathan/ppREGENIE/Data/client.pstats')
  File "/home/swaminathan/miniconda3/envs/ppregenie_env/lib/python3.11/cProfile.py", line 17, in run
    cProfile.run('main()', '/home/swaminathan/ppREGENIE/Data/client.pstats')
  File "/home/swaminathan/miniconda3/envs/ppregenie_env/lib/python3.11/cProfile.py", line 17, in run
    return _pyprofile._Utils(Profile).run(statement, filename, sort)
           ^^^^^^^^^^    return _pyprofile._Utils(Profile).run(statement, filename, sort)
^^^^^^^^^^^^^        ^^^^^^^^^^^^^^^^^^^   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^  File "/home/swaminathan/miniconda3/envs/ppregenie_env/lib/python3.11/profile.py", line 54, in run
    prof.run(statement)
^^^^^^^^^^^^^^  File "/home/swaminathan/miniconda3/envs/ppregenie_env/lib/python3.11/cProfile.py", line 96, in run
    return self.runctx(cmd, dict, dict)
^^^^^^^^^^          ^^^^^^^^^
 ^^^^^^^^^^^^^^^^  File "/home/swaminathan/miniconda3/envs/ppregenie_env/lib/python3.11/profile.py", line 54, in run
    prof.run(statement)
^^^^^^^^^^^^  File "/home/swaminathan/miniconda3/envs/ppregenie_env/lib/python3.11/cProfile.py", line 96, in run
    return self.runctx(cmd, dict, dict)

  File "/home/swaminathan/miniconda3/envs/ppregenie_env/lib/python3.11/cProfile.py", line 101, in runctx
           exec(cmd, globals, locals)
    ^^^^^^^^^^  File "<string>", line 1, in <module>
  File "/mnt/beegfs/home/swaminathan/ppREGENIE/ppREGENIE/cluster_blocked/client.py", line 533, in main
^^^^^^^^^    GWAS_lib.send_data_to_server(client_socket, masked_X[_], p)
  File "/mnt/beegfs/home/swaminathan/ppREGENIE/ppREGENIE/cluster_blocked/GWAS_lib.py", line 75, in send_data_to_server
^^^^^^^^^
    client_socket.sendall(data_size)
ConnectionResetError  File "/home/swaminathan/miniconda3/envs/ppregenie_env/lib/python3.11/cProfile.py", line 101, in runctx
    exec(cmd, globals, locals)
: [Errno 104] Connection reset by peer
  File "<string>", line 1, in <module>
  File "/mnt/beegfs/home/swaminathan/ppREGENIE/ppREGENIE/cluster_blocked/client.py", line 533, in main
    GWAS_lib.send_data_to_server(client_socket, masked_X[_], p)
  File "/mnt/beegfs/home/swaminathan/ppREGENIE/ppREGENIE/cluster_blocked/GWAS_lib.py", line 75, in send_data_to_server
    client_socket.sendall(data_size)
ConnectionResetError: [Errno 104] Connection reset by peer
srun: error: tcml-node19: task 0: Exited with exit code 1
srun: error: tcml-node20: task 0: Exited with exit code 1
Job script finished
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=873167.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
